steps:
  - name: ':rspec: unit-test'
    command: script/unit_test.sh
    agents:
      location: aws
  - name: ':rspec: integration-test'
    command: script/integration_test.sh
    agents:
      location: aws

  - wait

  - name: ':gem: build'
    command: script/build.sh
    agents:
      location: aws
