steps:
  - name: ':gem: build'
    command: script/build.sh
    agents:
      location: aws
    env:
      KUMO_KEISEI_VERSION: $BUILDKITE_BUILD_NUMBER
  - name: ':rspec: unit-test'
    command: script/unit_test.sh
    agents:
      location: aws
