#!/usr/bin/env ruby

require_relative '../lib/kumo_keisei'

def run_command(cmd)
  puts cmd
  puts `#{cmd}`
  raise "non zero exit code" if $?.exitstatus != 0
end

tag = File.read(File.expand_path('../VERSION', __FILE__)).strip

run_command "git tag #{tag}"
run_command "git push origin #{tag}"
